### PR TITLE
Dpat 521 module loader

### PR DESCRIPTION
**Pull request by tlisonbee**

### CODE REVIEW

**Comment by xoltar** [comment]
Could you please summarize the differences between this and the old loader?

**Comment by tlisonbee** [comment]
Sure, the main goal of this loader was to simplify loading so that we can enable Spark lazy execution, chaining several Spark plugins together, more easily.  

Some secondary goals were:
- Simplify the configuration for a module.  For example, values that are used as keys to other values,  reduce layering of config, etc.
- Separate configuring of modules from other uses of config.
- Add unit tests.  Later we'd also like to add integration tests to make sure nobody breaks things accidentally.
- Make it easy for the whole team to understand.
- Help enable getting rid of uber jars, they are taking forever to build and are difficult to debug.
- Help enable the copying of jars to HDFS so that we don't need to submit them with each Yarn job.

**Comment by xoltar** [comment]
Thanks, that makes sense. So there are going to be no uberjars anymore?
Dependencies will be stored as loose jars (e.g. one for slf4j, one for
slick, etc..)?

**Comment by tlisonbee** [comment]
Yes, a collection of loose jars, plugins will know what jars they need, SparkCommandPlugins will share the same list of jars because they are going to be executed together in the same Yarn job.

**Pull request merged**
